# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn_device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raspberry',
            old_name='boolean',
            new_name='bl',
        ),
    ]
